FROM quay.io/refgenomics/docker-ubuntu:14.04

MAINTAINER Danya Hassan <dhassan24@kgi.edu>

RUN apt-get install -y samtools
RUN apt-get install -y bwa
RUN apt-get install -y cyvcf2
RUN apt-get install -y bcftools

# Convenience commands
ADD ../Scripts/pipelinefile.ipynb pipelinefile.ibynb
RUN chmod +x pipelinefile.ibynb